### ISSUE TITLE
Adding masks to fields on forms, cruds and blocks.

### ISSUE THREAD

**Issue by GustavoFenilli** [litstack/litstack#102]
I looked the documentation and didn't find a way to add mask inputs to the fields nor the tables.

I would like to suggest the addition of masks, both for input and tables, making it easier to add some fields like telephones and money.

Making it return a plain text without the mask and making it possible to add the same mask to the table, so we have database integrity.

**Comment by cbl** [comment]
Hey @GustavoFenilli, this is a good Idea! Haven't thought about masks yet. Have you used masks yourself in the past? I found [cleave.js](https://nosir.github.io/cleave.js/) which looks promising.

**Comment by GustavoFenilli** [comment]
Looked and it looks great, worked fine in opera that some masks do not work. And it has a lot of customization using blocks and delimiters.

**Comment by cbl** [comment]
Added input masks in https://github.com/litstack/litstack/pull/127 using Cleave.js
