### ISSUE TITLE
Installation bug - model_has_roles

### ISSUE THREAD

**Issue by laravelbap** [litstack/litstack#105]
In my application for roles and permissions im using https://github.com/JosephSilber/bouncer . Parts of tables have common names with spatie permissions that is used here in litstack.

In config/permissions.php i changed prefix of tables to "lit_" this partially worked but i got bug. Name  model_has_roles i used in code instead of config . 

in InstallCommand.php on line ~ 117 there is

```
DB::table('model_has_roles')->insert([
            'role_id'    => Role::where('name', 'admin')->where('guard_name', 'lit')->first()->id,
            'model_type' => 'Lit\\Models\\User',
            'model_id'   => DB::table('lit_users')->where('email', 'admin@admin.com')->first()->id,
        ]);
```

  should be 

```
DB::table(config('permission.table_names.model_has_roles'))->insert([
            'role_id'    => Role::where('name', 'admin')->where('guard_name', 'lit')->first()->id,
            'model_type' => 'Lit\\Models\\User',
            'model_id'   => DB::table('lit_users')->where('email', 'admin@admin.com')->first()->id,
        ]);

```

second issue is here: src/Permissions/Models/ModelRole.php  

```
class ModelRole extends Model
{
    /**
     * Database table name.
     *
     * @var string
     */
    protected $table = 'model_has_roles';
}

```

should be 

```
class ModelRole extends Model
{

    public function getTable()
    {
        return config('permission.table_names.model_has_roles', parent::getTable());
    }
    
}
```

I will try to create pull-request for this

**Comment by cbl** [comment]
Fixed in https://github.com/litstack/litstack/pull/106

The Model in `Role` in the spatie package has exactly the `getTable` method you are mentioned: https://github.com/spatie/laravel-permission/blob/db4a4dbc5f1a3c394a67564f490e67f2a04135e1/src/Models/Role.php#L31
