### ISSUE TITLE
Use repeatable outside of block

### ISSUE THREAD

**Issue by albertpratomo** [litstack/litstack#107]
Hi, I'm wondering if it's possible to use repeatable outside of block field. Consider the following design:

![image](https://user-images.githubusercontent.com/25815584/100625239-8f3e5c00-3324-11eb-9369-d31520a83be4.png)

I'd like to enable the user to configure what the text of "shop our garments" button should be and where it should link to. I can make a `ButtonRepeatable` that extends from `Fields/Block/Repeatable`. In `ButtonRepeatable` I will ask for "button_text" field and "button_link" field. Then ideally in the config I want to do something like this:
```
public function show(CrudShow $page)
    {
        $page->card(function($form) {
            $form->input('title'); // Basic text input field.
            $form->button('button_1'); // My ButtonRepeatable field.
            $form->button('button_2'); // My ButtonRepeatable field.

            // Alternative syntax:
            $form->repeatable('button_1', ButtonRepeatable::class);
        });
    }
```

Not sure if this is already possible.. Maybe there is a work around to enable this?

**Comment by cbl** [comment]
I think what you want here is presets containing a set of form fields that can be added at any point. There are many ways to do that one way would be to create a Preset class with static methods containing all the presets you need, like so:

```php
class FormPresets
{
    public static function button($form)
    {
        $form->input('button_title');
        $form->input('button_link');
    }
}
```

This could now be used in a form like this:
```php
$page->card(function($form) {
    FormPresets::button($form);
});
```

**Comment by albertpratomo** [comment]
Yeah, that's possible.. But can I group the data in an array?

Ideally I want a data structure like this:
```
[
    'button_1' => ['title' => 'Foo', 'link' => 'Bar'],
]
```

**Comment by cbl** [comment]
You could add an attribute to your model:

```php
public function getButtonAttribute()
{
    return (object) [
        'title' => $this->button_title,
        'link' => $this->button_link,
    ];
}
```

**Comment by albertpratomo** [comment]
Hmm I'm using `Ignite\Crud\Models\Repeatable` for this one. Would be nice if I don't have to override the `Repeatable` model..

**Comment by albertpratomo** [comment]
@cbl Any ideas?

**Comment by cbl** [comment]
I don't really see why you want to use the repeatable model in this Case since it is a Static Button. If it wouldnt be Static you could Just use the Block field.

**Comment by albertpratomo** [comment]
The main reason is because I want to "group" 2 fields together and call it a button field, I'd like the values to be in 1 array. Also I want this button field to be reusable in other forms.

I think the concept of Repeatable fits well with this, just that it needs to be usable outside of a Block.

Is this requiring a big change in the architecture?

**Comment by albertpratomo** [comment]
Currently I have a complex reusable repeatable which I call `SectionRepeatable`. It has a bunch of fields in its form.

It would be nice that I can reuse this `SectionRepeatable` staticly and not having to duplicate the code where I define the the fields..

**Comment by cbl** [comment]
The only way to reach this would be through a relation: You could create a new Repeatable entry in the database when storing the Model and make the fields of this repeatable editable using a relationship. However I think this is not a good solution.

Isn't the `Preset` class solving the problem for you?

**Comment by albertpratomo** [comment]
With the `Preset` class, I have to add this accessor to the `Repeatable` model:
```
public function getButtonAttribute()
{
    return (object) [
        'title' => $this->button_title,
        'link' => $this->button_link,
    ];
}
```

I would like to not have to modify the `Repeatable` model..

**Comment by cbl** [comment]
Unfortunately this is not easily possible, you would have to abstract the getters and setters of the model like in the `LitFormModel`, I don't think this is worth the effort.

**Comment by albertpratomo** [comment]
Ok, so conclusion is for now Litstack can't support `Repeatable` being used outside of `Block` field? And as alternative we can use the `Preset` class, correct?

**Comment by cbl** [comment]
Yes
