### ISSUE TITLE
Select field info and hint

### ISSUE THREAD

**Issue by albertpratomo** [litstack/litstack#109]
![image](https://user-images.githubusercontent.com/25815584/100637976-c10aef00-3333-11eb-9309-642532d17cc1.png)

1. The `info()` of select field seems to be not working: `$form->select('section_type')->info('Some info')` -> no tooltip shown.
2.  Is it possible to show a custom modal using `info()` or `hint()`? Or maybe I need to do `$form->component('custom-component')` instead?

**Comment by cbl** [comment]
Hey @albertpratomo, the info tooltip works fine for me. 🤔

To your second question: You need to add a component for this.

**Comment by cbl** [comment]
Closing as it seem to be working
