### ISSUE TITLE
keepOriginalImageFormat for LitMediaForm's medias

### ISSUE THREAD

**Issue by albertpratomo** [litstack/litstack#111]
Would be nice if `Ignite\Crud\Models\Traits\HasMedia` calls `keepOriginalImageFormat()` during `registerMediaConversions()`. At the moment my JPG images are being converted to PNG for the conversions.

Also I think `Ignite\Crud\Models\Concerns\HasMedia` is not needed because `Traits\HasMedia` has been used by `LitFormModel`.

I can make a PR for this if you guys agree with this proposal. 😃

**Comment by cbl** [comment]
Yes I also notices this while working on this https://github.com/litstack/litstack/pull/108
You can contribute to the branch where we are working on the new cropper. 

Also I was thinking of something like field events, so you could manipulate the media upload, maybe like this:

```php
use Ignite\Crud\Fields\Media\Image;

Image::uploading(function($request, $media) {
    $media->keepOriginalImageFormat();
});
```

Also we are thinking of dropping media library in 4.x

**Comment by albertpratomo** [comment]
Ok, will do that.

Not sure yet if field events will be much needed (for my use case at least). But yeah it's nice to have a way to customize the conversions that are happening to the media.

**Comment by laravelbap** [comment]
I don't think that complete dropping media library is good. This gives out of the box nice features. Maybe make it just optional and don't require and if app will require media can use media library or devs can implement same interface as media library.

In my case then i would be able dont use media at all in some entities.
