### ISSUE TITLE
Add more heading to WYSIWYG field

### ISSUE THREAD

**Issue by albertpratomo** [litstack/litstack#117]
Would be nice if the WYSIWYG field also support `h1 - h6` headings.

Currently:
![image](https://user-images.githubusercontent.com/25815584/101413037-e2477e80-38e3-11eb-9a18-4943e59c2faf.png)

**Comment by cbl** [comment]
Would accept a pr.

Do you have usecases where you write a text with a h1 or h6? shouldn't the h1 header be the headline of the page and avoid nesting deeper than h4? Just curious.

**Comment by jannescb** [comment]
> Would accept a pr.
> 
> Do you have usecases where you write a text with a h1 or h6? shouldn't the h1 header be the headline of the page and avoid nesting deeper than h4? Just curious.

This is exactly why we decided to excluded the h1 initially. An h1 should only be set once, so an input field is the better solution.

**Comment by albertpratomo** [comment]
Hmm ok, that makes sense..

**Comment by jannescb** [comment]
Functionality has been added [120](https://github.com/litstack/litstack/pull/120) 👍
