### ISSUE TITLE
Add maximum amount of repeatables in the Block field

### ISSUE THREAD

**Issue by albertpratomo** [litstack/litstack#119]
![image](https://user-images.githubusercontent.com/25815584/101482935-bcf45800-3957-11eb-91cd-b1df090be1af.png)

Would be nice if package user can define the maximum amount of repeatables in the Block field. In the case above, I'd like to allow maximum 4 testimonies, then I'd like the "+ testimony" button to be disabled with some text "Maximum items have been reached".

**Comment by cbl** [comment]
This is definitely a thing, I don't have the time to implement this at the moment will do when this is needed in a project, would also accept a pr.
