### ISSUE TITLE
Add whenIn method for conditional field

### ISSUE THREAD

**Issue by albertpratomo** [litstack/litstack#121]
Currently I have this code in my config:
```
$form->input('title')
   ->when('section_type', 'Hero')
   ->orWhen('section_type', 'ParagraphImage')
   ->orWhen('section_type', 'Slider');
```

I think it will be more elegant if I can do:
```
$form->input('title')
   ->whenIn('section_type', ['Hero', 'ParagraphImage', 'Slider']);
```

This is inspired by [`whereIn()`](https://laravel.com/docs/8.x/collections#method-wherein) method in Collection. 

What do you guys think? If this proposal is approved I'd like to try submit a PR for it.

**Comment by cbl** [comment]
This is good, looking forward to your pr!
