### ISSUE TITLE
"array_key_exists() expects parameter 2 to be array" for custom_properties 

### ISSUE THREAD

**Issue by Jacq** [litstack/litstack#123]
I have populate a database with some images using the litstack 3.2.0 version (php 7.4 and laravel 8.0). I get an error here:

https://github.com/litstack/litstack/blob/00e4d784c6ceabaf6c19bf3945fe95df1c8748ae/src/Crud/Models/Traits/HasMedia.php#L86

I see in the database that custom_properties is just an empty array [] but in the above function the returned value is null.
While browsing the trace (see below) I notice here the conversion for custom_properties: https://github.com/litstack/litstack/blob/00e4d784c6ceabaf6c19bf3945fe95df1c8748ae/src/Crud/Models/Media.php#L77

The problem there is that parent::getAttribute('custom_properties') returns the empty array [], and then the array_key_exists tries to get from there again the 'custom_properties' key (array_key_exists($name, $properties)), which does not exist, so this if is not taken and the functions returns null causing the below exception.
I'am not quite sure about the rationale of the Media.php getAttribute custom_properties particular case, should the database contain a array of arrays or there is an innecesary conversion in either the Media.php or HasMedia.php functions?

Cheers,
Jacq

<pre>
local.ERROR: array_key_exists() expects parameter 2 to be array, null given {"exception":"[object] (ErrorException(code: 0): array_key_exists() expects parameter 2 to be array, null given at /var/app/backend/vendor/litstack/litstack/src/Crud/Models/Traits/HasMedia.php:86)
[stacktrace]
#0 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(2, 'array_key_exist...', '/var/app/backen...', 86, Array)
#1 /var/app/backend/vendor/litstack/litstack/src/Crud/Models/Traits/HasMedia.php(86): array_key_exists('crop', NULL)
#2 /var/app/backend/vendor/litstack/litstack/src/Crud/Models/Traits/HasMedia.php(60): App\\Models\\Project->applyCrop(Object(Spatie\\MediaLibrary\\Conversions\\Conversion), Object(Ignite\\Crud\\Models\\Media))
#3 /var/app/backend/vendor/spatie/laravel-medialibrary/src/InteractsWithMedia.php(596): App\\Models\\Project->registerMediaConversions(Object(Ignite\\Crud\\Models\\Media))
#4 /var/app/backend/vendor/spatie/laravel-medialibrary/src/Conversions/ConversionCollection.php(63): App\\Models\\Project->registerAllMediaConversions(Object(Ignite\\Crud\\Models\\Media))
#5 /var/app/backend/vendor/spatie/laravel-medialibrary/src/Conversions/ConversionCollection.php(27): Spatie\\MediaLibrary\\Conversions\\ConversionCollection->addConversionsFromRelatedModel(Object(Ignite\\Crud\\Models\\Media))
#6 /var/app/backend/vendor/spatie/laravel-medialibrary/src/Conversions/ConversionCollection.php(18): Spatie\\MediaLibrary\\Conversions\\ConversionCollection->setMedia(Object(Ignite\\Crud\\Models\\Media))
#7 /var/app/backend/vendor/spatie/laravel-medialibrary/src/Support/UrlGenerator/UrlGeneratorFactory.php(28): Spatie\\MediaLibrary\\Conversions\\ConversionCollection::createForMedia(Object(Ignite\\Crud\\Models\\Media))
#8 /var/app/backend/vendor/spatie/laravel-medialibrary/src/MediaCollections/Models/Media.php(67): Spatie\\MediaLibrary\\Support\\UrlGenerator\\UrlGeneratorFactory::createForMedia(Object(Ignite\\Crud\\Models\\Media), 'preview')
#9 /var/app/backend/vendor/litstack/litstack/src/Crud/Models/Media.php(23): Spatie\\MediaLibrary\\MediaCollections\\Models\\Media->getUrl('preview')
#10 /var/app/backend/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php(494): Ignite\\Crud\\Models\\Media->getUrlAttribute(NULL)
#11 /var/app/backend/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php(1595): Illuminate\\Database\\Eloquent\\Model->mutateAttribute('url', NULL)
#12 /var/app/backend/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php(407): Illuminate\\Database\\Eloquent\\Model->transformModelValue('url', NULL)
#13 /var/app/backend/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php(386): Illuminate\\Database\\Eloquent\\Model->getAttributeValue('url')
#14 /var/app/backend/vendor/litstack/litstack/src/Crud/Models/Media.php(69): Illuminate\\Database\\Eloquent\\Model->getAttribute('url')
#15 /var/app/backend/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1786): Ignite\\Crud\\Models\\Media->getAttribute('url')
#16 /var/app/backend/app/Http/Resources/Project.php(29): Illuminate\\Database\\Eloquent\\Model->__get('url')
#17 /var/app/backend/vendor/laravel/framework/src/Illuminate/Collections/HigherOrderCollectionProxy.php(60): App\\Http\\Resources\\Project->toArray(Object(Illuminate\\Http\\Request))
#18 [internal function]: Illuminate\\Support\\HigherOrderCollectionProxy->Illuminate\\Support\\{closure}(Object(App\\Http\\Resources\\Project), 1)
#19 /var/app/backend/vendor/laravel/framework/src/Illuminate/Collections/Collection.php(630): array_map(Object(Closure), Array, Array)
#20 /var/app/backend/vendor/laravel/framework/src/Illuminate/Collections/HigherOrderCollectionProxy.php(61): Illuminate\\Support\\Collection->map(Object(Closure))
#21 /var/app/backend/vendor/laravel/framework/src/Illuminate/Http/Resources/Json/ResourceCollection.php(100): Illuminate\\Support\\HigherOrderCollectionProxy->__call('toArray', Array)
#22 /var/app/backend/app/Http/Resources/ProjectCollection.php(18): Illuminate\\Http\\Resources\\Json\\ResourceCollection->toArray(Object(Illuminate\\Http\\Request))
#23 /var/app/backend/vendor/laravel/framework/src/Illuminate/Http/Resources/Json/JsonResource.php(95): App\\Http\\Resources\\ProjectCollection->toArray(Object(Illuminate\\Http\\Request))
#24 /var/app/backend/vendor/laravel/framework/src/Illuminate/Http/Resources/Json/ResourceResponse.php(39): Illuminate\\Http\\Resources\\Json\\JsonResource->resolve(Object(Illuminate\\Http\\Request))
#25 /var/app/backend/vendor/laravel/framework/src/Illuminate/Http/Resources/Json/JsonResource.php(221): Illuminate\\Http\\Resources\\Json\\ResourceResponse->toResponse(Object(Illuminate\\Http\\Request))
#26 /var/app/backend/vendor/laravel/framework/src/Illuminate/Http/Resources/Json/ResourceCollection.php(115): Illuminate\\Http\\Resources\\Json\\JsonResource->toResponse(Object(Illuminate\\Http\\Request))
#27 /var/app/backend/vendor/laravel/framework/src/Illuminate/Routing/Router.php(765): Illuminate\\Http\\Resources\\Json\\ResourceCollection->toResponse(Object(Illuminate\\Http\\Request))
#28 /var/app/backend/vendor/laravel/framework/src/Illuminate/Routing/Router.php(752): Illuminate\\Routing\\Router::toResponse(Object(Illuminate\\Http\\Request), Object(App\\Http\\Resources\\ProjectCollection))
#29 /var/app/backend/vendor/laravel/framework/src/Illuminate/Routing/Router.php(692): Illuminate\\Routing\\Router->prepareResponse(Object(Illuminate\\Http\\Request), Object(App\\Http\\Resources\\ProjectCollection))
#30 /var/app/backend/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#31 /var/app/backend/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#32 /var/app/backend/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#33 /var/app/backend/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php(127): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#34 /var/app/backend/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php(63): Illuminate\\Routing\\Middleware\\ThrottleRequests->handleRequest(Object(Illuminate\\Http\\Request), Object(Closure), Array)
#35 /var/app/backend/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Routing\\Middleware\\ThrottleRequests->handle(Object(Illuminate\\Http\\Request), Object(Closure), '60', '1')
#36 /var/app/backend/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#37 /var/app/backend/vendor/laravel/framework/src/Illuminate/Routing/Router.php(694): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#38 /var/app/backend/vendor/laravel/framework/src/Illuminate/Routing/Router.php(669): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#39 /var/app/backend/vendor/laravel/framework/src/Illuminate/Routing/Router.php(635): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#40 /var/app/backend/vendor/laravel/framework/src/Illuminate/Routing/Router.php(624): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#41 /var/app/backend/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(166): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#42 /var/app/backend/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#43 /var/app/backend/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#44 /var/app/backend/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#45 /var/app/backend/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#46 /var/app/backend/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#47 /var/app/backend/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#48 /var/app/backend/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#49 /var/app/backend/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(87): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#50 /var/app/backend/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#51 /var/app/backend/vendor/fruitcake/laravel-cors/src/HandleCors.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#52 /var/app/backend/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fruitcake\\Cors\\HandleCors->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#53 /var/app/backend/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#54 /var/app/backend/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#55 /var/app/backend/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#56 /var/app/backend/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(141): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#57 /var/app/backend/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(110): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#58 /var/app/backend/public/index.php(55): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#59 {main}
"}

</pre>

**Comment by cbl** [comment]
Thanks. I fixed this in https://github.com/litstack/litstack/commit/c4542cb3028f1f229ab8d679f7dccd2873aac285. You can now update to [v3.2.1](https://github.com/litstack/litstack/releases/tag/v3.2.1) then it should work.

**Comment by Jacq** [comment]
That was fast, thanks!
