### ISSUE TITLE
Field validation bug on update

### ISSUE THREAD

**Issue by kacol24** [litstack/litstack#124]
I noticed when using rules, on update it tries to validate all fields. But only dirty fields are being sent as payload on update. This throws validation errors for fields that are not being updated.

For example:
Title (rules: required)
Description (rules: required)

On create the rules works fine, it validates that both fields are required. But on update, if you only change the description, this throws "The Title field is required." validation error.

It's expected that the Title field is not going to be validated or at least pass the required validation rule since the field is not changed and has value.

**Comment by cbl** [comment]
Hey @kacol24, this is the expected behaviour. In your case you need to set `creationRules` and `updateRules` where to only set all fields to `required` when creating a new entry.

```php
$field->creationRules('required') // Only applies on creation
    ->updateRules('some-other-rule') // Only applies on update
    ->rules('min:2') // Applies on creation an update
```

This has already been asked in https://github.com/litstack/litstack/issues/17

**Comment by kacol24** [comment]
Oops, that's embarrassing. I missed that issue! Definitely my fault for not searching thoroughly.
