### ISSUE TITLE
How to use image field to show in index?

### ISSUE THREAD

**Issue by tamaskeringer** [litstack/litstack#133]
1.

use Ignite\Crud\Models\Traits\HasMedia;
use Spatie\MediaLibrary\HasMedia as HasMediaContract;
class Post  extends Model implements HasMediaContract
{ 
    use HasMedia;

...
    public function getImagesAttribute()
    {
        return $this->getMedia('images');
    }
}

2.

    public function index(CrudIndex $page)
    {
        $page->table(function ($table) {

            $table->col('title')->value('{title}')->sortBy('title');
            $table->image('Image')->src('{images.url}');

}}

3.

    public function show(CrudShow $page)
    {
        $page->card(function($form) {
            $form->image('images')->title('images');

}}
![Screenshot_2020-12-20 Bejegyzések - Litstack](https://user-images.githubusercontent.com/12703936/102710528-43dbf580-42b3-11eb-8896-95a73569d142.png)
![Screenshot_2020-12-20 Bejegyzés - Litstack](https://user-images.githubusercontent.com/12703936/102710552-56562f00-42b3-11eb-83e7-ab2ced6b31cf.png)

result attached in images

Can YOU help me what can be the problem?

**Comment by cbl** [comment]
Hey @tamaskeringer, your image attribute returns a collection so multiple images. You may only show a single image in your index table. I would recommend to add another attribute that returns the first image of you collection:

```php
public function getImageAttribute()
{
    return $this->getMedia('images')->first();
}
```

Then should be able to preview the image in your index table:

```php
$table->image('Image')->src('{image.url}');
```

Also I would recommend to display a conversion of your image and not the full image:

```php
$table->image('Image')->src('{image.conversion_urls.md}');
```
