### ISSUE TITLE
Select Field in Modal

### ISSUE THREAD

**Issue by needhelp12345** [litstack/litstack#138]
Cant acces the value from a Select field in a Modal(litstack Action)
Steps to reproduce .
Create an Action.
Paste this code:
`class MyAction
{
    public function modal(ActionModal $modal)
    {
        $modal->form(function($form) {
        $form->select('article_type')
    ->title('Type')
    ->options([
        1 => 'News',
        2 => 'Info',
    ])
    ->hint('Select the article type.');
    });
    }

    public function run(Collection $models,AttributeBag $attributes)
    {
            $stdout = fopen('php://stdout', 'w');
            fwrite($stdout, $attributes->article_type . PHP_EOL);
        
    }
}`

2.Dont see anything in laravel console

**Comment by cbl** [comment]
Hey @needhelp12345,

I reproduced this and I am able to access the field values:

```php
    public function modal(ActionModal $modal)
    {
        $modal->form(function ($form) {
            $form->select('article_type')
                ->title('Type')
                ->options([
                    1 => 'News',
                    2 => 'Info',
                ])
                ->hint('Select the article type.');
        });
    }

    /**
     * Run the action.
     *
     * @param  Collection   $models
     * @return JsonResponse
     */
    public function run(Collection $models, AttributeBag $attributes)
    {
        dd($attributes->article_type);

        return response()->success('Action executed.');
    }
```

Where are you placing the action?
