### ISSUE TITLE
Sorting Index-Table Column bug(s)

### ISSUE THREAD

**Issue by jannescb** [litstack/litstack#153]
Sorting Index-Table Column is only showing the gt->sm icon.

Also, sorting multiple times is creating a duplicate of the icon each time sorted:

<img width="1067" alt="Bildschirmfoto 2021-01-25 um 20 16 00" src="https://user-images.githubusercontent.com/17292622/105754616-96f83680-5f4a-11eb-9988-a27c003fd6c1.png">

**Comment by cbl** [comment]
Fixed
