### ISSUE TITLE
Select doesn't show text when using readonly function

### ISSUE THREAD

**Issue by kostopravby** [litstack/litstack#162]
Example:
```
$form->select('customer_id')
                    ->title('Customer')
                    ->readonly()
                    ->options(Customer::all()
                    ->mapWithKeys(fn ($customer) => [$customer->id => $customer->phone_number])->toArray())
                    ->width(1 / 2);
```
It shows 'id' in select field like this. 
![image](https://user-images.githubusercontent.com/29959329/106923627-56a17100-671f-11eb-851d-321b1cb3e112.png)
If I remove readonly(), then I see 'phone_number'.

**Comment by cbl** [comment]
Hey @kostopravby, thanks. This should fix the bug https://github.com/litstack/litstack/commit/9066026604cdd8bf1be702fc3b0173eb5aa95115
