### ISSUE TITLE
Relation table and data field

### ISSUE THREAD

**Issue by kostopravby** [litstack/litstack#163]
In parent controller I have table with following code:
`
public function index(CrudIndex $page)
{
$page->table(function ($table) {
$table->date('created_at','d-m-Y H:m')->small();
}
`
![image](https://user-images.githubusercontent.com/29959329/106954756-4b613c00-6745-11eb-9129-c9940fc001e5.png)

Relation table looks like this
![image](https://user-images.githubusercontent.com/29959329/106954817-62079300-6745-11eb-9525-734df10aa00f.png)

```
$page->card(function ($form) {
                $form->relation('XXXX')->readOnly()->title('Orders')
            ->use(XXXX::class);
            });
```

**Comment by kostopravby** [comment]
Also column's titles are missing.

**Comment by cbl** [comment]
@kostopravby You can add `->showTableHead()` to your relation field.

**Comment by cbl** [comment]
Would accept a pr.

In the meantime you could add the field directly in the relation preview instead of using `use`.
