### ISSUE TITLE
Charts bug

### ISSUE THREAD

**Issue by kostopravby** [litstack/litstack#169]
I created new user.
"Last 24 hours", "Last 7 days", "Last 30 days" filters don't show this.
![image](https://user-images.githubusercontent.com/29959329/107979166-22576b80-6fcf-11eb-9415-c959a5314296.png)
![image](https://user-images.githubusercontent.com/29959329/107979193-2edbc400-6fcf-11eb-804b-7a94eac71566.png)
But if I select "Today" or other filters, then I see newly created user.
![image](https://user-images.githubusercontent.com/29959329/107979285-5e8acc00-6fcf-11eb-9395-8948ae4ff27b.png)

I think that filters "Last ....." don't include today.

**Comment by kostopravby** [comment]
Also how to remove "K" in value
![image](https://user-images.githubusercontent.com/29959329/107979605-eb358a00-6fcf-11eb-8a4b-4acfc1f6ad93.png)

**Comment by cbl** [comment]
Fixes this in https://github.com/litstack/litstack/commit/b38407dff0d47f1d11cec75835bab716373a8679
