### ISSUE TITLE
Litstack action problem

### ISSUE THREAD

**Issue by j0ha** [litstack/litstack#171]
Hello, I think this is a bug.
I am trying to send an email to a model with an action in the CRUD table. The model has an attribute 'email'.
How it is explained in the docs I would think, that the run method in the action class, will receive, this model at which I clicked the action. Right?
But this isn't? Where is my error or did I miss something?

Here is the action:
`public function run(Collection $models)
{
    foreach($models as $model) {
        Mail::to($model->email)->send(new testEmail());
    }
}`
and the table:
` public function index(CrudIndex $page)
    {
        $page->table(function ($table) {
            $table->col('Id')->value('{id}')->sortBy('id');
            $table->col('Nutzername')->value('{username}')->sortBy('username');
            $table->action('Test', testEmail::class);
        })->search('username');
    }`

**Comment by cbl** [comment]
Hey, I fixed this in https://github.com/litstack/litstack/commit/3541ebe61d3ff9e1eb0941f48c58070a2b715ffa, I am going to Tag a Release tomorrow
