### ISSUE TITLE
CRUD action actions problem

### ISSUE THREAD

**Issue by j0ha** [litstack/litstack#174]
Hi, I discovered a new/old problem with v.3.4.3.
When I call an action with the "action" method in a CRUD, the action will not receive any model data. See picture one.
But when I call the same action with the "actions" method, the action will receive data. See picture two.
<img width="1686" alt="Bildschirmfoto 2021-03-05 um 13 40 59" src="https://user-images.githubusercontent.com/46874251/110117464-2b12b480-7db9-11eb-84f7-4559d67572eb.png">
<img width="1667" alt="Bildschirmfoto 2021-03-05 um 13 41 36" src="https://user-images.githubusercontent.com/46874251/110117496-36fe7680-7db9-11eb-97b7-50b2c22b3fa3.png">

**Comment by cbl** [comment]
Release tagged [3.4.4](https://github.com/litstack/litstack/releases/tag/v3.4.4)
