### ISSUE TITLE
Update Datetime field

### ISSUE THREAD

**Issue by kostopravby** [litstack/litstack#176]
$table->date('created_at', 'Y-m-d H:i') field does not use timezone offset from laravel config. 
maybe better to change in 
/litstack/src/Page/Table/Casts/CarbonColumn.php
to
`return (new Carbon($value))->setTimezone(config('app.timezone'))->format($this->format);`
Also some comments in this file just copied from MoneyCast file

**Comment by cbl** [comment]
Hey @kostopravby, why dont you create a pull request for this? ;)

**Comment by kostopravby** [comment]
don't see how. left for you.
