### ISSUE TITLE
Multiple filter options in the table

### ISSUE THREAD

**Issue by kostopravby** [litstack/litstack#181]
if I select more than one filter option I receive empty result.
for example https://demo.litstack.io/admin/orders
select providers Stripe and PayPal.

**Comment by cbl** [comment]
This was actually wrong in the corresponding order config: https://github.com/litstack/demo/commit/64a62b4efaf8db3b12779abd818b75dd045a6cb0#diff-e6463cdc55e7284640a94b89fd449fb706ea77e42234cedbbd5a6a65af64c09a

You cannot have the same query scope in different filter groups.
