### ISSUE TITLE
Image Cropper is throwing a vue error after repeated upload

### ISSUE THREAD

**Issue by aw-tansen** [litstack/litstack#191]
Steps to recreate:
1) Image is uploaded and cropped.
2) Image is removed
3) Another Image is uploaded in the same form.

<img width="1176" alt="Bildschirmfoto 2021-04-08 um 12 11 37" src="https://user-images.githubusercontent.com/71370078/114387264-82fbc280-9b92-11eb-9f6e-e58649c1e3d2.png">

**Comment by cbl** [comment]
@aw-tansen I wasn't able to reproduce this. I tried the following field inside and outside a repeatable. Also the browser I used was Chrome.

```php
$form->image('images')->maxFiles(5)->crop(4 / 3);
```

Also what litstack version did you use?

**Comment by cbl** [comment]
Safari is working for me as well.
