### ISSUE TITLE
Question: Composer dependencies

### ISSUE THREAD

**Issue by tomasnorre** [litstack/litstack#192]
Hi, 

Does a reason exist why the `friendsofphp/php-cs-fixer` is in `require` and not in `require-dev` instead. 
https://github.com/litstack/litstack/blob/3.x/composer.json#L19

Disclaimer: I  don't know litstack, just saw it presented in the Laravel DACH Meetup.

**Comment by tomasnorre** [comment]
I found it. 
https://github.com/litstack/litstack/blob/3.x/src/Support/helpers.php#L5

**Comment by cbl** [comment]
Yes, it is used to beautify generated php files. Maybe this should be optional. 🤔

**Comment by tomasnorre** [comment]
If you use it, in the main code it should be done as it is. Then it's not optional in my opinion.
