### ISSUE TITLE
Upload Image though WYSIWYG?

### ISSUE THREAD

**Issue by jcsoriano** [litstack/litstack#20]
Hi, this is an awesome package! Thank you for making it open source. Is it possible to upload images into the WYSIWYG?

**Comment by jannescb** [comment]
Hi, thanks for your feedback!
It is not possible right now. We played around with Base64-encoding which was working for small images but obviously limited...
For "mixed content" I would recommend [building a block](https://www.fjord-admin.com/docs/fields/blocks/) with repeatables for text and images. 

But we will definitely keep this feature in mind!

**Comment by Jacq** [comment]
> Maybe consider using https://github.com/ueberdosis/tiptap. [Statamic](https://github.com/ueberdosis/tiptap) is also using it for its' _bard_ field type.

It seems they are already using TipTap: https://litstack.io/docs/3.x/fields/wysiwyg

**Comment by cbl** [comment]
I am closing this for now since we are not planing to implement this at the moment. We would accept a pr if anyone need's image upload through the wysiwyg field anyway.
