### ISSUE TITLE
Add image during creation. 

### ISSUE THREAD

**Issue by Shipu** [litstack/litstack#231]
Add image during creation.

**Comment by Shipu** [comment]
@cbl can you please explain why you close this issue.

**Comment by cbl** [comment]
A Sufficient description of an issue is missing. I have no idea what your intention of opening this issue is.

**Comment by Shipu** [comment]
i want to add images when create operation. Currently add image when update operation. is there any way to support add images when create operation.

**Comment by cbl** [comment]
This is not possible at the moment, I would Accept a pr.
