### ISSUE TITLE
Accessors in crud table

### ISSUE THREAD

**Issue by EvvC** [litstack/litstack#256]
Hi! Can I use model accessors in tables? According to crud table documentation https://litstack.io/docs/3.x/crud/table#image it is possible, but neither image nor any accessor I've tried show any value. Thanks!
```
$table->image('Image')->src('{image.url}');
```
```
public function getImagesAttribute()
{
    return $this->getMedia('images')->first();
}
```

**Comment by saundefined** [comment]
Hm.. you can add `protected $appends = ['images']` to the model or use relations instead of accessor 🤔
