### ISSUE TITLE
Design files

### ISSUE THREAD

**Issue by Wulfheart** [litstack/litstack#64]
As you are also a design agency I assume that you have also sketch/rigmarole/adobeXD/etc. files for your components. Is there any possibility that you open source these? This would help if people wanted to recreate your UI e.g. TailwindCSS.

**Comment by cbl** [comment]
@Wulfheart That is a good idea! We are going to release some of the artwork soon.

**Comment by Wulfheart** [comment]
Can't wait to craft some beautiful tailwind components. 
Is it a full design system? Is there an estimate date of release? Is it possible to get the sizes?😀

**Comment by cbl** [comment]
I dont have a date yet. We are working on 3.0 which is going to be released soon. And with it the design files ;)

**Comment by uwesteffen** [comment]
> As you are also a design agency I assume that you have also sketch/rigmarole/adobeXD/etc. files for your components. Is there any possibility that you open source these? This would help if people wanted to recreate your UI e.g. TailwindCSS.

Hi Alex. 
seems like the topic went lost on the way to the designers. 
Right now the sketch file is a huge mess :D but I will keep the topic in mind and will prepare a sketch file we can provide. 
All the Best

**Comment by Wulfheart** [comment]
They are now available at https://github.com/litstack/art.
