### ISSUE TITLE
Using uuid instead of autoincrement

### ISSUE THREAD

**Issue by vipercs90** [litstack/litstack#69]
When using uuid instead of autoincrement, there is a problem with the lit: install command.

```
SQLSTATE[HY000]: General error: 1364 Field 'id' doesn't have a default value (SQL: insert into `lit_users` (`username`, `email`, `first_name`, `last_name`, `password`) values (admin, admin@admin.com, admin, , $2y$10$9ILfeH5oddVtDnqMNttoSeg/zl7/jVJ7DTTFDpfartWSxnc3NgWvC))
```

```php
Ignite\Foundation\Console\InstallCommand

protected function defaultUser()
    {
        if (config('app.env') == 'production') {
            return;
        }
        if (DB::table('lit_users')->where('username', 'admin')->orWhere('email', 'admin@admin')->exists()) {
            return;
        }

        DB::table('lit_users')->insert([
            'username'   => 'admin',
            'email'      => 'admin@admin.com',
            'first_name' => 'admin',
            'last_name'  => '',
            'password'   => bcrypt('secret'),
        ]);
        DB::table('model_has_roles')->insert([
            'role_id'    => Role::where('name', 'admin')->where('guard_name', 'lit')->first()->id,
            'model_type' => 'Lit\\Models\\User',
            'model_id'   => DB::table('lit_users')->where('email', 'admin@admin.com')->first()->id,
        ]);

        $this->info('created default admin (email: admin@admin.com, password: secret)');
    }
```

If you use an eloquent model, then this problem can be avoided.

Only user model Lit\Models\User is available for extension. How do I extend my lit model to use a UUID?

**Comment by cbl** [comment]
Hello, at the moment you can edit the migration `2020_00_00_000000_create_lit_users_table.php`. You may create users using a seeder if you have modified the migration.

**Comment by vipercs90** [comment]
> Hello, at the moment you can edit the migration `2020_00_00_000000_create_lit_users_table.php`. You may create users using a seeder if you have modified the migration.

But the problem is not that I cannot generate the necessary tables, but that I add UuuiTrait to the LIT models.
For example model Ignite\Crud\Models\Form

![image](https://user-images.githubusercontent.com/5518560/94779676-c81f8a80-03e0-11eb-820e-45082083279c.png)


This is how it is done in the spatie / laravel-permission package
![image](https://user-images.githubusercontent.com/5518560/94779912-13399d80-03e1-11eb-8985-d6fd444726e5.png)

https://spatie.be/docs/laravel-permission/v3/advanced-usage/uuid

**Comment by Wulfheart** [comment]
What is the benefit of using uuid in this special case?

**Comment by vipercs90** [comment]
> What is the benefit of using uuid in this special case?

I need uuid since the application will use the database cluster.
There are problems with autoincrement in a multi-master cluster.

**Comment by cbl** [comment]
I would accept a pr for implementing the option of changing the model classes in the config. At the moment I dont have the time to work on this myself.
