### ISSUE TITLE
Upload multiple image fields and attachments

### ISSUE THREAD

**Issue by Jacq** [litstack/litstack#75]
An initial remark regarding the docs for others, currently the documentation explains to use the image field here: https://litstack.io/docs/3.x/fields/image
There are slight differences between docs and the actual code created by the 'php artisan lit:crud -m Name' command.
The main difference is that de doc examples to use a collection of images while the code generated is for one:
<code>
public function getImageAttribute()
    {
        return $this->getMedia('image')->first();
    }
</code>
I have follow the above strategy to add multiple different images fields categories (with no problems to upload or preview) such as:
<code>
public function getFeatureAttribute()
    {
        return $this->getMedia('feature')->first();
    }
public function getLogoAttribute()
    {
        return $this->getMedia('logo')->first();
    }
</code>
Is the above the proper way to achieve this?

Also I would like to add attachments that are not images to models, it seems is possible using Spatie media-library using different media collections. I did not found a reference to this use of attachments in Litstack docs and currently the drag/drop control is filtering "not image" files so I have not dig more into this.
Is this attachment (not images) files to model easily achievable with the current code or will need some internal tuning?
Cheers,
Jacq

**Comment by cbl** [comment]
Hey @Jacq 

If you want to have mutliple Images for one Attribute you need to remove the `first` method in your model and set `maxFiles` Files to the desired maximum amount of Images that can be uploaded to the collection.

There is a file field at the moment, it is not documented at the Moment since it is not fully finished. However feel free to try it out and improve it yourself. We also accept apr

**Comment by cbl** [comment]
Accidentially hit the Close button on my phone 😅

**Comment by Jacq** [comment]
Thanks!, found the File field and works well for my purpose.
I have not yet forked the code and look deep, I am more used to laravel + SPA vue, but will try to get into the livewire to be able to provide userful pr.
Cheers,

**Comment by cbl** [comment]
Sounds great, most of the litstack sourcecode ist laravel + Vue tho
