### ISSUE TITLE
How to use "Block" field for HasMany relation

### ISSUE THREAD

**Issue by albertpratomo** [litstack/litstack#80]
Hi, thanks for the upgrade to Litstack! I have a question about a feature I wanted in my admin panel.

So I have `Store` model with `HasMany` relation to `OpeningHour` model.

```
// App\Models\OpeningHour.php

attributes:
- store_id (int)
- day (int)
- open_time (time)
- close_time (time)
```

I'm hoping to use the `Block` field so admin can input the opening hours of a store. I've gotten this far:
![image](https://user-images.githubusercontent.com/25815584/96513960-3da1ac80-1263-11eb-82cd-5ee0a3c24e87.png)

And the `StoreConfig@show`:
```
$page->card(function ($form) {
            $form->block('opening_hours')->repeatables(function ($rep) {
                $rep->add('Opening Hour', function ($form, $preview) {
                    $form->select('day')
                        ->title('Day')
                        ->options(DayEnum::asSelectArray())
                        ->width(6);

                    $form->dt('open_time')
                        ->title('Open Time')
                        ->onlyDate(false)
                        ->formatted('LT')
                        ->width(3);

                    $form->dt('close_time')
                        ->title('Close Time')
                        ->onlyDate(false)
                        ->formatted('LT')
                        ->width(3);
                });
            });
        });
```

However I'm a bit stuck, how can I save this to `opening_hours` table with the correct `store_id`?

**Comment by albertpratomo** [comment]
I see.. I'm afraid that this will make it hard for me to query things. For example, if I want to index all stores that are open on Sunday.

Or do you think it will still be fairly easy? @cbl

**Comment by albertpratomo** [comment]
@cbl As an alternative, can I use the "relation" field then? But I wish to have a Day dropdown, Open time input, and Close time input for each OpeningHour model..

**Comment by cbl** [comment]
Querying the repeatables from a block field is indeed not that easy since all values are stored as json in one column. You could create a relation field with a form. By that you are able to edit the relationship data in a modal:
```php
$form->relation('opening_hours')->form(function($form) {
    $form->select('day')
              ->title('Day')
              ->options(DayEnum::asSelectArray())
              ->width(6);

    $form->dt('open_time')
              ->title('Open Time')
              ->onlyDate(false)
              ->formatted('LT')
              ->width(3);

    $form->dt('close_time')
               ->title('Close Time')
               ->onlyDate(false)
               ->formatted('LT')
               ->width(3);
));
```

I am currently working on the feature where you can create a the model for a relationship directly like via the block field.

**Comment by albertpratomo** [comment]
> I am currently working on the feature where you can create a the model for a relationship directly like via the block field.

This sounds exactly like the feature I need, thank you!
