### ISSUE TITLE
toggle() in table not works CRUD

### ISSUE THREAD

**Issue by vipercs90** [litstack/litstack#83]
Documentation
To edit the boolean state of a moel directly in a table, a switch can be displayed in a column using toggle. The name of the corresponding attribute must be specified as the first parameter. In addition, the routePrefix for the update route must be specified, if the table is built in a CRUD or form config, simply use the config function routePrefix.
```php
$table->toggle('active')
    ->label('Live')
    ->routePrefix($this->routePrefix())
    ->sortBy('active');
```

My code
```php
 /**
     * Build index page.
     *
     * @param \Ignite\Crud\CrudIndex $page
     * @return void
     */
    public function index(CrudIndex $page)
    {
        $page->table(
            function ($table) {
                $table->col('slug')->value('{slug}')->sortBy('slug');
                $table->col('Name')->value('{name}')->sortBy('name');
                $table->col('Title')->value('{title}')->sortBy('title');
                $table->col('Description')->value('{description}')->sortBy('description');
                $table->toggle('is_active')
                    ->label('Active')
                    ->routePrefix($this->routePrefix())
                    ->sortBy('is_active');
            }
        )->search('title');
    }
```

I get error message
"The PUT method is not supported for this route. Supported methods: GET, HEAD."

What am I doing wrong?

**Comment by cbl** [comment]
Hey, this commit fixed the bug https://github.com/litstack/litstack/commit/9ce883cde5d7c33573c677efeaf05bb5fb1d4f32

Also you dont have to add a `routePrefix` any more:

```php
$table->toggle('is_active')
           ->label('Active')
           ->sortBy('is_active');
```
