### ISSUE TITLE
Relationship field is not shown in the table CRUD

### ISSUE THREAD

**Issue by vipercs90** [litstack/litstack#84]
Code
```php
//in PageConfig -> public function index(CrudIndex $page)
$table->relation('Template')
  ->related('template')
  ->value('{name}')
  ->routePrefix($this->routePrefix())
  ->sortBy('template.name');

// in Page model
/**
 * @return BelongsTo
 */
public function template()
{
        return $this->belongsTo(PageTemplate::class, 'page_template_id', 'id');
}
```

![image](https://user-images.githubusercontent.com/5518560/97458498-96a4cb00-195c-11eb-9e83-5211622bfbd2.png)

**Comment by cbl** [comment]
Hey, this commit should fix the bug https://github.com/litstack/litstack/commit/52880ec84edf31aa303f498e31e999fb5f02662e

The value needs to be changed to `template.name`. This was wrong in the documentation.
Also I changed You dont have to use the `related` method and the `routePrefix`. Just set the first parameter to the relation method:

```php
$table->relation('template')
  ->value('{template.name}')
  ->sortBy('template.name');
```
