### ISSUE TITLE
use users table and model instead of lit_users

### ISSUE THREAD

**Issue by damieneskimo** [litstack/litstack#85]
Hi there. In the case of installing Litstack in an existing project, what's best solution to use the existing users table and App\Models\User model. I tried to change the auth.php configuration file to use users table and the model class, merge Lit\Models\User model methods and add some necessary fields for Litstack to users table  and replace the occurrences of Lit\Models\User in lit directory, but running a type hint error, which the CrudRouter require a Lit\Models\User in the source code.  [https://github.com/litstack/litstack/blob/3.x/src/Crud/CrudRouter.php#L190](https://github.com/litstack/litstack/blob/3.x/src/Crud/CrudRouter.php#L190)

So can you please help me to point the right way to solve the problem? Thanks.

**Comment by cbl** [comment]
Hi @damieneskimo 

using your own authentication system is not possible at the moment. I recommend to use the standard `lit_users` table for litstack. You can find and edit the Model in `lit/app/Models/User`.

Could you please describe why you would want to user `users` instead of `lit_users`? We might think of implementing custom authentication systems if there is a good reason for it.

**Comment by damieneskimo** [comment]
Hi @cbl 

Thanks for your reply. Since I have already got the public member login/dashboard in place, I thought it's better to continue using the current `users` table and model. And adding a separate `lit_users` table and model could make it hard to manage? or I just need to rename the table name from `users` to `lit_user`?

**Comment by cbl** [comment]
Hi @damieneskimo 

This pr https://github.com/litstack/litstack/pull/90 adds support to use a different guard to grand access to the litstack applicaiton.

You can specify which users should have access to litstack like this:

```php
class Kernel extends LitstackKernel
{
    // ...

    /**
     * Determine if an authenticated user has access to the litstack application.
     *
     * @param  Authorizable $user
     * @return bool
     */
    public function authorize(Authorizable $user): bool
    {
        return in_array($user->email ,[
            'lennart.carbe@gmail.com'
            // Specify more email addresses with access to litstack...
        ]);
    }
}
```
