### ISSUE TITLE
Dynamic crud table filters

### ISSUE THREAD

**Issue by kacol24** [litstack/litstack#86]
To filter a crud table, according to the [docs](https://litstack.io/docs/3.x/crud/index#filter) it says to use Laravel's model scope. From what I understand, the scope values needs to be hardcoded in the model.

![image](https://user-images.githubusercontent.com/11154858/97662674-3fad0c00-1aaa-11eb-8192-ad0349a0400c.png)

Say for example this use case:
- Post belongsTo PostCategory
- PostCategory hasMany Post

On PostConfig@index I want to filter the Post by PostCategory (which was queried from db), how do you achieve that?

**Comment by jannescb** [comment]
Thats funny, we discussed exactly that just yesterday.
@cbl will be looking at "dynamic filters" and "default filters" next week, we will keep you updated here 👍

**Comment by cbl** [comment]
Dynamic CRUD table filters are now available in v3.1.0 https://github.com/litstack/litstack/releases/tag/v3.1.0
