### ISSUE TITLE
demo credentials are wrong

### ISSUE THREAD

**Issue by Guelguin** [litstack/litstack#87]
The prefilled credentials in the demo login page displays "invalid credentials" message
https://demo.litstack.io/admin/login

**Comment by cbl** [comment]
Thanks demo is now available again.

**Comment by WasserEsser** [comment]
@cbl Sorry, deleted the admin user, demo is broken again.

**Comment by dacastro4** [comment]
So... people keep deleting the admin user. Aren't we developers? lol.. the demo is broken again
