### ISSUE TITLE
Parse LitFormModel to simple array

### ISSUE THREAD

**Issue by albertpratomo** [litstack/litstack#97]
Hi, I want to use Litstack with Inertia. The idea is using `Form` and passing it as `page` prop in the vue component.

I got it working, but the passed `page` prop is too complex:
```
{
  "sections": [],
  "id": 1,
  "config_type": "Lit\\Config\\Form\\Pages\\HomeConfig",
  "form_type": "show",
  "collection": "pages",
  "form_name": "home",
  "value": {
    "sections": []
  },
  "order_column": null,
  "created_at": "2020-11-25T11:06:40.000000Z",
  "updated_at": "2020-11-25T11:06:53.000000Z",
  "translation": {
    "en": {
      "title": "Holaaaa",
      "body": "&lt;p&gt;yes sir&lt;/p&gt;"
    }
  },
  "translations": [
    {
      "id": 1,
      "lit_form_id": 1,
      "locale": "en",
      "value": {
        "title": "Holaaaa",
        "body": "&lt;p&gt;yes sir&lt;/p&gt;"
      }
    }
  ],
  "media": []
}
```

Ideally what I would like would be:
```
{
   sections: [],
   title: "Holaaaa",
   body: "&lt;p&gt;yes sir&lt;/p&gt;"
}
```

Is there already a solution for this? Or do you have a suggestion how to achieve this?

**Comment by cbl** [comment]
Hey @albertpratomo 

You could filter the array like this:
```php
return array_merge(
    $page->value,
    $page->translation[app()->getLocale()] ?? []
);
```

**Comment by albertpratomo** [comment]
With that solution I'm unable to get the `repeatables` of the form.

I ended up making a `JsonResource` for `LitFormModel`:
```
<?php

namespace Lit\Http\Resources;

use Illuminate\Http\Resources\Json\JsonResource;
use Illuminate\Support\Collection;

class LitFormResource extends JsonResource
{
    /**
     * Transform the resource into an array.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return array
     */
    public function toArray($request)
    {
        $fields = $this->fields->map(fn($field) => $field->id);
        
        $data = [];

        foreach ($fields as $field) {
            $value = $this[$field];

            if ($value instanceof Collection) {
                $value = $value->map(fn($repeatable) => new $this($repeatable));
            }

            $data[$field] = $value;
        }

        return $data;
    }
}
```

@cbl Do you have a suggestion to make this more elegant?

**Comment by cbl** [comment]
Hey, I see, you need the data from all form fields including relationships. The solution you found is pretty good.

I'm thinking about adding a method that does this for you like:
```php
return $form->resource();
```

**Comment by albertpratomo** [comment]
I would gladly contribute a PR 😄 . Should I?

**Comment by albertpratomo** [comment]
We can also just override the `toArray()` method. So `$form->toArray()` will be cleaner. What do you think? @cbl

**Comment by cbl** [comment]
Shure always happy about pr's!!

**Comment by cbl** [comment]
I would recommend to create a `resource` method in the `Ignite\Crud\Models\LitFormModel`. This could then be used in the `toArray` method By that `resource` includes only form field data and toArray all the data including id, etc.
